### ISSUE TITLE
Loot command shows incorrect stats for 2-handed weapons

### ISSUE THREAD

**Issue by Vuks69** [aikaterna/gobcog#102]
**Reproduction:**
1. equip a 2-handed weapon
2. loot chests one by one until you find any weapon or offhand

**Issue**
This may be hugely misleading, as a player might for example expect their new one handed katana with 20 ATT to be more useful than their 2-handed greatsword showing as 15 ATT, while the actual stat the greatsword provides is 30 ATT when equipped.

![image](https://user-images.githubusercontent.com/51289041/74693772-7a596780-51ed-11ea-8208-1a2e35f61d4e.png)
![image](https://user-images.githubusercontent.com/51289041/74693774-7b8a9480-51ed-11ea-814a-03cdc2c1f58e.png)

**Comment by Drapersniper** [comment]
Note to self: Fixed
