### ISSUE TITLE
Old Tinkerer Items converted to normal items?

### ISSUE THREAD

**Issue by Emre-desertbird** [aikaterna/gobcog#105]
Probably just a one-time only issue but I feel like sharing it anyway, so it doesn't happen again.
![IMG_20200218_153022](https://user-images.githubusercontent.com/38984901/74745189-c5ae5d00-5263-11ea-84b8-042a02c329cb.jpg)

Hoooo...ly = tinkerer item before new release.
Asdf = new tinkerer item, because the old one was converted to a normal one.

**Comment by Emre-desertbird** [comment]
Don't want to open a new issue, but we are getting a lot of dragons lately... Is that because we got very high stats or is there something broken?

**Comment by aikaterna** [comment]
Tinkerers were never supposed to have more than one tinkered item, that is why those changed to normal, it was a bugfix. The dragon thing is currently being worked on. Please open separate issues for separate questions that don't have much to do with each other. Thanks for the issues and comments so far.
