### ISSUE TITLE
Update to weapons removed all currently owned set weapons

### ISSUE THREAD

**Issue by kwando1313** [aikaterna/gobcog#106]
With the update to the weapons, all the weapons which were previously set weapons have now changed into normal weapons.

So, for example, my {Gear_Set: Masterwork Ebony Wand} and {Gear_Set: Elven Mithril Dagger} have both been changed to normal items.

**Comment by Drapersniper** [comment]
This is a 1 time error, and its already been fixed on an upcoming patch

**Comment by Drapersniper** [comment]
Fixed in #104

**Comment by aikaterna** [comment]
Please open another issue if you still have problems with this after updating the cog.
