### ISSUE TITLE
Negaverse cooldown triggers if there is no int-value after the command

### ISSUE THREAD

**Issue by Emre-desertbird** [aikaterna/gobcog#107]
![Capture](https://user-images.githubusercontent.com/38984901/74885558-2928af80-5376-11ea-83f0-4c15d68080c0.PNG)

**Comment by Drapersniper** [comment]
Note to self: Fixed

**Comment by Drapersniper** [comment]
Fixed in #104

**Comment by aikaterna** [comment]
Please open another issue if you still have problems with this after updating the cog.
