### ISSUE TITLE
Loadout show returns an error

### ISSUE THREAD

**Issue by grayconcaves** [aikaterna/gobcog#108]
![loadout show](https://user-images.githubusercontent.com/11259621/74948876-df080280-5437-11ea-9e62-78c6163e1f6d.png)

Loadout show returns this error. Something about the charsheet? As well as one that happens whenever I load adventure.

**Comment by Drapersniper** [comment]
Note to self .. This has been fixed already

**Comment by Drapersniper** [comment]
Fixed in #104

**Comment by aikaterna** [comment]
Please open another issue if you still have problems with this after updating the cog.
