### ISSUE TITLE
XP-Gain of Ranger way too high

### ISSUE THREAD

**Issue by Emre-desertbird** [aikaterna/gobcog#111]
I know that experience gain depends on many things like rebirths, stats etc.
But I don't think the xp-boost from ranger pets should be THAT high.
My friend just rebirthed and got 38000xp with a pet (with 36% bonus) from a fight where I (1 less rebirth, much higher stats, bard) got just 24000xp. I don't this that's normal...

**Comment by hellokansas** [comment]
Disagree.

**Comment by Drapersniper** [comment]
You filed this on a saturday, Saturday do have 2x XP.

**Comment by Drapersniper** [comment]
so yes it is intention depending on monster, stats, players, rebirths

**Comment by Emre-desertbird** [comment]
So first that's for pointing out the xp-boost, totally forget that.
But the 2x Xp still doesn't really change anything, sind everyone profits from it.

I'm just asking if you could check if there is something wrong, since he should have gotten only 1,35 as much as I did, and not 1,6... Only his pet and ONE rebirth were reasons he should have gotten more xp than I did, so that didn't seem right to me. 
So yea, if you checked and didn't find any problem, I'm okey with it.

**Comment by ysdenz** [comment]
I don't see any problem with Rangers. Rangers don't have damage bonuses like the other classes and heavily relies on raw stats and items. Besides, taming a pet is also RNG

**Comment by Emre-desertbird** [comment]
Not my point. What I'm trying to say is, that they are probably gaining more than they should... Could be wrong tho.

**Comment by ysdenz** [comment]
24,000 x 1.36 = 32,640. 
38,000 - 32,640 = 5360
5,360 might came with the rebirth difference.

**Comment by Drapersniper** [comment]
@Emre-desertbird  I’ll double check, but that does sound right as @ysdenz pointed out the numbers.

I’ll update this once I have a look over the code.

**Comment by Drapersniper** [comment]
After some further look nothing in the code jumped out at me that indicated the ranger XP is broken, and upon doing some lock testing and reserve engineering the formulas everything in looking okay, do note rangers are supposed to gain a significant amount of XP when compared to other classes, they gain no damage or diplomacy bonus, so this is their class benefit

**Comment by Emre-desertbird** [comment]
Alright, if there is no problem after double checking, I'm okey with it. I take my issue back...
