### ISSUE TITLE
Convert epic is useless

### ISSUE THREAD

**Issue by mattpilf** [aikaterna/gobcog#122]
Right now the chance of legendary item from epic is 5%-10%, and chance of legendary item from legendary chest is 55-100%.

Given 50 epic chest you're expected 2.5-5 legendary items, or if you convert to one legendary item .55-1. You also would get 0 epic items which means no money if sold.

One could drastically lower the conversion, change the odds for legendary items in either chest, or add a small chance of set items in legendary chest making the trade off worth it for established players.

**Comment by Drapersniper** [comment]
Im strongly agains allowing set items in legendary chests.

That being said yes the concert of the convert command has been raised a few times recently,  in my eyes the reason it is there is to help users with too many chests if they just want a few extra ones.

Your suggestion about tweaking the ods, is a valid suggestion.

Another option would be get rid of the convert command entirely and disable the ability to concert chests, @aikaterna  imo this would make things simpler,  its not as if chests are as rare as they once where, for character with more rebirth.

**Comment by Drapersniper** [comment]
https://github.com/aikaterna/gobcog/pull/126
Does improve the epic rares now

**Comment by aikaterna** [comment]
Some values were recently adjusted in #126. Please give it a try and see what you think.
