### ISSUE TITLE
Winning negaverse while looting an item

### ISSUE THREAD

**Issue by Emre-desertbird** [aikaterna/gobcog#123]
So while looting an item (without having selected if you want to equip it or not) you can still go to the negaverse.
The problem is, if you win in the negaverse you don't actually gain the levels or the levels you just got get reseted again.

The levelup in the picture is from negaverse.

![IMG_20200226_004647](https://user-images.githubusercontent.com/38984901/75297974-879bd500-5831-11ea-8254-e9949329db55.jpg)

**Comment by ysdenz** [comment]
this was the same issue with loot as well and **draper** fixed it by locking other commands to prevent overwriting data

**Comment by Emre-desertbird** [comment]
I see, didn't know that, thanks for pointing out!
