### ISSUE TITLE
[Suggestion] [p] backpack <rarity> command

### ISSUE THREAD

**Issue by ysdenz** [aikaterna/gobcog#124]
Since backpack sellall <rarity> works well, I think it would be also great if bot can also show the item list by rarity.

**Comment by Drapersniper** [comment]
I like this idea a lot, been suggested in different formats for example https://github.com/aikaterna/gobcog/issues/109

Currently FR will be on a temporary hold until a UX PR is completed just fixing any typoes or UI discrepancies, but after that im more than happy to implement this.
