### ISSUE TITLE
Stuck Adventures Prevent Looting/Equipping/Skill Commands

### ISSUE THREAD

**Issue by AaronBurrSir** [aikaterna/gobcog#130]
Happens quite often where you'll start an adventure and it will just get stuck on the countdown, and from then on it will prevent you from being able to do any looting, equipping or skill setting until someone literally restarts the entire Adventure bot across all discord servers. 

This is a hard progression blocker as you can participate in adventures but can never equip anything or increase your stats or open loot boxes.

**Comment by Drapersniper** [comment]
Do you have the traceback that happened at the moment it got stuck? Without it is nearly impossible to fix the underlying issue as it bot reproducing for me or other bots I’m aware of

**Comment by aikaterna** [comment]
Are you a user of Trustybot or is this on your own bot?

**Comment by AaronBurrSir** [comment]
Trustybot. I wont have a traceback or anything like that. But this happens often, requiring the owner of Trustybot to restart the bot entirely or for an admin of the server to remove a lock (which can break things even more).

**Comment by AaronBurrSir** [comment]
Also I would be shocked to see another bot using Adventure more than Trustybot is at the moment, so I wouldnt be so quick to dismiss these issues of "oh it's just that bots problem".

**Comment by aikaterna** [comment]
> so I wouldnt be so quick to dismiss these issues of "oh it's just that bots problem".

I didn't, I'm asking for information. Thanks, I'll talk to Trusty about this instead.

**Comment by AaronBurrSir** [comment]
Sorry about that, still love the Adventure cog and all the work you aren't getting paid for lol!

**Comment by Drapersniper** [comment]
Stale issue, can be closed as it is no longer reproducing (or at least no new reports on the latest version 3.1.5)
