### ISSUE TITLE
[p]loadout not functional

### ISSUE THREAD

**Issue by ysdenz** [aikaterna/gobcog#131]
loadout show won't show the list
loadout equip doesn't equip any and clears my equipped items.
upon checking thru **[p]adventure**, bonuses from **set items** (set items that were suppose to be equipped is in effect)

Upon checking the backpack, items aren't lost during the bug.

steps to reproduce:
- fully equip the item set (i tried on Slobberknocker set)
- save the loadout (**[p]loadout save [name]**)
- loadout saves successfully
- do **[p]loadout equip [name]**
- bot output only shows the raw stats from rebirth and levels gained, without the item stats added (issue no 1)
- doing **[p]stats** will show that nothing is equipped (issue no 2)
- lastly, doing **[p]loadout show** will not show any output (issue no 3)

note - users who have never saved any loadout will normally produce the output which is 
**you don't have any loadouts saved**. Then after saving one loadout, **[p]loadout show** will return no output.

**Comment by Drapersniper** [comment]
https://github.com/aikaterna/gobcog/pull/136
Should fix this

**Comment by aikaterna** [comment]
This seems to be resolved. Please open another issue if you see more loadout problems.
