### ISSUE TITLE
Raise the Credit Cap

### ISSUE THREAD

**Issue by AaronBurrSir** [aikaterna/gobcog#132]
With players reaching increasing rebirth heights, currency collection becomes increasingly easier and makes it very easy to hit the 10million limit very quickly. 

I would recommend increasing this limit by 10x to 100 million to stay in line with top level players and their rebirth levels. 

Also decrease the time limit for successful negaverse attempts as a way to create a credit sink as cart purchases and rebirth costs are so miniscule in regards to the amount of time it takes to make that sort of money.

**Comment by kwando1313** [comment]
Very much agree, as a player, I’m hitting the cap fairly often, as there’s not much I can really do with money because, well, the cart is a big ripoff and there’s nothing else money is used for...

**Comment by Drapersniper** [comment]
This is not related to adventure, if you are using Cat mention this on the support channel for cat

**Comment by Drapersniper** [comment]
To develop on this further, the currency limiter is not set on by adventure it is set by the bot

**Comment by aikaterna** [comment]
As Draper mentioned, if you are a user of my bot named cat, the economy cap is 10 million credits. No one has approached the 10 million limit recently, so I am going to assume you are playing adventure on another bot. Nonetheless, the bot owners themselves are responsible for the top limit of credits that you can use or hold on the bot. If you are reaching an economy cap for credits, please speak with the owner of the bot about adjusting that value. If you are playing adventure on my bot, cat, the economy cap will not be raised past 10 million.

**Comment by AaronBurrSir** [comment]
To be clear, I think the vast majority are using Trustybot.

**Comment by aikaterna** [comment]
Then you will need to talk to Trusty if you are using Trustybot.
