### ISSUE TITLE
Set items still old set items stats

### ISSUE THREAD

**Issue by mattpilf** [aikaterna/gobcog#133]
Set items I have didn't seem adjusted to the new buff. Idk if new items are switched but hard to say. I've killed like 30 dragons and still no set chest but I might be unlucky there.

**Comment by Drapersniper** [comment]
New items will have the buff for stats,  the set bonus will always be applied to match the latest version,  due to how items were currently stored updating the item start for existing items is non trivial however is it something that will get looked at in a future update

**Comment by Drapersniper** [comment]
#136  should address this

**Comment by aikaterna** [comment]
Items have been adjusted.
