### ISSUE TITLE
Bard Skill [p]Music does not do anything.

### ISSUE THREAD

**Issue by KTCAOP** [aikaterna/gobcog#138]
so with music - KTCAOP :game_die:(10) + :musical_note: 34 + :speech_left:97
Without Music - KTCAOP :game_die:(10) + :musical_note: 33 + :speech_left:97

With Music - KTCAOP :game_die:(11) + :musical_note: 31 + :speech_left:92
Without Music - KTCAOP :game_die:(16) + :musical_note: 33 + :speech_left:92

watdakwan and Darius can confirm.

**Comment by Drapersniper** [comment]
As explained in discord, this is not entirely the case case,  Music skills allows you to get aditional points based on your rebirths,   which in both cases you did.

On the second block you got 5 extra points based on your roll, and the bonus was only 2 points higher.

Nevertheless I did address the damade for the Wizzard, Berserker and Bard on #136
