### ISSUE TITLE
Feature Request - Clarification for [p]backpack sellall

### ISSUE THREAD

**Issue by KTCAOP** [aikaterna/gobcog#157]
If you type [p]backpack sellall [invalid argument]

Where [invalid argument] could be @username, a misspelling such as normals or norms, all items in the backpack are sold outside of set items.

Would it be possible that when sellall is triggered, to add a confirmation box stating "You are about to sell all items, are you sure?" with the check mark and cross box?

**Comment by deXxterlab97** [comment]
> If you type [p]backpack sellall [invalid argument]
> 
> Where [invalid argument] could be @username, a misspelling such as normals or norms, all items in the backpack are sold outside of set items.
> 
> Would it be possible that when sellall is triggered, to add a confirmation box stating "You are about to sell all items, are you sure?" with the check mark and cross box?

Agreed. A man has sacrificed themselves by selling all of their legendaries, gaining 2 million credit back but eventually lose all in negaverse. Such a sad world.

**Comment by Drapersniper** [comment]
Fixed

**Comment by Drapersniper** [comment]
Fixed in #165

**Comment by aikaterna** [comment]
Should be resolved with the merge of #165
