### ISSUE TITLE
Loop depr in Red 3.4+

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#158]
/.../Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py:4619: DeprecationWarning: Explicitly passing the loop will not work in Red 3.4+
  start_adding_reactions(adventure_msg, self._adventure_actions, ctx.bot.loop)

**Comment by Drapersniper** [comment]
Done

**Comment by Drapersniper** [comment]
Fixed in #165

**Comment by aikaterna** [comment]
Should be resolved with the merge of #165
