### ISSUE TITLE
[Change Log] Broken Link

### ISSUE THREAD

**Issue by Menteroth** [aikaterna/gobcog#160]
https://github.com/aikaterna/gobcog/blob/master/Change%20logs%20for%203.0.0.md

**Comment by Drapersniper** [comment]
@Menteroth  what exactly is broken?
where ? because from here: https://github.com/aikaterna/gobcog
If i click on 3.0.0 Update, it takes me to the change logs fine

**Comment by Menteroth** [comment]
![image](https://user-images.githubusercontent.com/24851042/79081454-d4723700-7d1d-11ea-9690-6ce6b54ef415.png)

**Comment by Drapersniper** [comment]
Ah well okay that line can just be fully remove by whoever next pr to adventure @aikaterna  or @TrustyJAID, since we have a breakdown of change logs below

**Comment by Menteroth** [comment]
Ah okay. I was using that link as an alias for info for members of the new changes, from old Adventure. But then it suddenly stopped working and couldn't find it again. I guess I missed to click the 3.0.0 link. 
Glad to have it "back" again hehe.

**Comment by Drapersniper** [comment]
Fixed

**Comment by Drapersniper** [comment]
Fixed in #165

**Comment by aikaterna** [comment]
Should be resolved with the merge of #165
