### ISSUE TITLE
Doing damage equal to hp doesn't yield a win

### ISSUE THREAD

**Issue by DariusStClair** [aikaterna/gobcog#162]
Doing damage equal to hp doesn't yield a win due to rounding so wohooo issue 👯‍♂️ 
![Annotation 2020-04-20 043305](https://user-images.githubusercontent.com/52074319/79736849-0ce6b780-82c0-11ea-9fea-a97be8d95195.png)

I know Draper wants to touch it but needs reminder <3

**Comment by aikaterna** [comment]
Seems like this is present in negaverse too (a push equals a loss).

**Comment by Drapersniper** [comment]
Fixed

**Comment by Drapersniper** [comment]
Fixed in #165

**Comment by aikaterna** [comment]
Should be resolved with the merge of #165
