### ISSUE TITLE
Taming Guardian of Nazarick accidently

### ISSUE THREAD

**Issue by Dark-lame** [aikaterna/gobcog#163]
I didn't meet any of the char sheet requirements for naz, but I happened to have its favourite food and I tamed it. I don't think this is intentional. 
![screenshotofnaz](https://user-images.githubusercontent.com/64549497/80625379-205df500-8a1b-11ea-8c30-3148ae16bd21.PNG)
Character sheet ^

**Comment by Drapersniper** [comment]
Fixed

**Comment by Drapersniper** [comment]
Fixed in #165

**Comment by aikaterna** [comment]
Should be resolved with the merge of #165
