### ISSUE TITLE
Auto-Release Pet Error

### ISSUE THREAD

**Issue by LordChanning** [aikaterna/gobcog#168]
![Screenshot (3830)](https://user-images.githubusercontent.com/39933493/81621249-26ed5480-93ab-11ea-9f05-5cce60927a1f.png)

Instead of auto-releasing the pet, one of my members with Albedo is unable to use the stats command or participate in any adventures.  Nothing shows up when stats is executed and the attached error shows up in the console

**Comment by boopatnyte** [comment]
![6A0D3FF8-9F06-43B7-BC3B-579DD02BE778](https://user-images.githubusercontent.com/64026529/81625836-412d2f80-93b7-11ea-9f07-baf323875c27.jpeg)

Here’s an attempt to negaverse with the pet auto release issue.

**Comment by boopatnyte** [comment]
![76049B7F-5833-4A97-B379-C2C0101CBC32](https://user-images.githubusercontent.com/64026529/81629856-66bf3680-93c1-11ea-8f96-8c0de64070bc.png)

This is what happened when I tried to spawn an adventure immediately followed by someone else who was able to. And for context I had the Albedo pet with ~500 stats in all categories with my gear. I wore legendaries in all slots except full groovinator set. I am rebirth 24, max lvl of 210.
