### ISSUE TITLE
Persuading a monster result in a loss if the points are exact equal

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#173]
![Screenshot_20200513-222343_Discord](https://user-images.githubusercontent.com/31835797/81855881-a07e7180-9568-11ea-89a1-7f9f4b4224ec.jpg)

**Comment by KTCAOP** [comment]
This can be seen in both persuasion and in damage dealing.

I want to say it is more or less due to rounding errors based on prefix multipliers, but as a rule we have established that if damage = HP/MP, we will lose.
