### ISSUE TITLE
Transcended monster does not give set chest upon defeating it with attacks

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#175]
![Screenshot_20200514-020717_Discord](https://user-images.githubusercontent.com/31835797/81874933-c0715d80-9587-11ea-86aa-69a1ce5405eb.jpg)

**Comment by deXxterlab97** [comment]
Here's another one
![Screenshot_20200514-210455_Discord](https://user-images.githubusercontent.com/31835797/81969435-a63a8c80-9626-11ea-8aa5-c8c49f1770f0.jpg)

**Comment by LordChanning** [comment]
![Screenshot (3944)](https://user-images.githubusercontent.com/39933493/82099925-b786a600-96c5-11ea-9be8-5a000f1d0816.png)
![Screenshot (3942)](https://user-images.githubusercontent.com/39933493/82099924-b6ee0f80-96c5-11ea-8e42-0b3c57458ff0.png)

![Screenshot (3947)](https://user-images.githubusercontent.com/39933493/82099926-b786a600-96c5-11ea-85f3-0e3ea3c262e1.png)
![Screenshot (3948)](https://user-images.githubusercontent.com/39933493/82099930-b8b7d300-96c5-11ea-962d-b1d2428c4ddf.png)


Some of my members have encountered this issue as well
