### ISSUE TITLE
Where do I find the bot?

### ISSUE THREAD

**Issue by Brando8** [aikaterna/gobcog#177]
My friends and I are sadly leaving our old server and creating our own. The only thing we really miss is the bot. Where do I find it to add to my server?

**Comment by aikaterna** [comment]
What bot are you talking about?

**Comment by Brando8** [comment]
We got it figured out. Feel free to delete the post.

**Comment by aikaterna** [comment]
![image](https://user-images.githubusercontent.com/20862007/82281712-de074400-9946-11ea-9b69-29263caa614a.png)
