### ISSUE TITLE
Suggestion - Increased Clarity in Attempts to Capture Pets

### ISSUE THREAD

**Issue by KTCAOP** [aikaterna/gobcog#178]
In order to make it more clear where the failure is when you fail to capture a pet, I suggest the following:

Change
https://github.com/aikaterna/gobcog/blob/master/adventure/adventure.py#L3634
to else:

Remove
https://github.com/aikaterna/gobcog/blob/master/adventure/adventure.py#L3643-L3651

A small QoL buff that may give a different message to help reduce the sanity loss in attempting to capture pets (and also can lead to increased clarity if it was a stat/roll issue or just being not lucky enough to catch a pet). Seeing just "the pet escaped" for hours while attempting to catch a pet can definitely be a sanity drain.

**Comment by aikaterna** [comment]
Catching pets should be easier now. I am not sure what you are suggesting with the removal of these lines and the change you mentioned.

**Comment by Drapersniper** [comment]
should this be closed now?

**Comment by aikaterna** [comment]
As I haven't heard more from my other question here, then I suppose so. Pet catching was adjusted to be a bit less brutal in a previous patch.
