### ISSUE TITLE
Bug with the rangers

### ISSUE THREAD

**Issue by RED541** [aikaterna/gobcog#180]
Since a moment, rangers can't tame a pet, the pet always escape.

It may be a problem with the can_catch variable which is always false except if we have the set required even if the pet doesn't require any set (L3584).

**Comment by deXxterlab97** [comment]
It just takes an awful longer time to tame a pet. My friend spent hours without taming it. On the bright side there's no cool down for [p]pet

**Comment by sirenondine** [comment]
I have the same problem on my server.

**Comment by Drapersniper** [comment]
Just to stop any more uneeded noise ...
Yes Pet taming is currently broken, but it will be fixed by #181 when that is merged. for now just wait.

**Comment by aikaterna** [comment]
Issue is resolved.
