### ISSUE TITLE
Adventure cog randomly stops working

### ISSUE THREAD

**Issue by sleepymanakete** [aikaterna/gobcog#186]
There's a problem where after doing adventures a couple of times, trying to start a new one and the bot will say there's an adventure running even though it already ended. I believe the timer goes away so to the bot, it runs forever. To fix it, I have to reload the cog. I don't really use it so I'm testing it out to see if I can trigger the issue. 
![dsfdf](https://user-images.githubusercontent.com/30272172/83199371-464fe580-a0fe-11ea-8a4a-4236ce74f96d.png)
![fdhfd](https://user-images.githubusercontent.com/30272172/83199392-51a31100-a0fe-11ea-9307-7abf66550bf8.png)

**Comment by deXxterlab97** [comment]
I don't have problem on my bot or aika's bot enough. Check what's wrong with your bot

**Comment by sleepymanakete** [comment]
I think updating my bot solved it

**Comment by sleepymanakete** [comment]
sorry for reopening but the command is doing this again. I don't know what's wrong with it.
