### ISSUE TITLE
Add unquip all command

### ISSUE THREAD

**Issue by explodingnew** [aikaterna/gobcog#191]
Hello. Is it possible to add a command !unequip all  ?
Thanks

**Comment by aikaterna** [comment]
Once #161 is resolved, you can save an empty loadout and use that to unequip items. Leaving this open in case I decide to make an unequip all command instead.

**Comment by aikaterna** [comment]
Going to be lazy and say you can save an empty loadout once you have unequipped all your items, and then use loadout equip to equip an empty loadout.
