### ISSUE TITLE
Double Adventures 

### ISSUE THREAD

**Issue by LordChanning** [aikaterna/gobcog#194]
![Screenshot_3848](https://user-images.githubusercontent.com/39933493/84852237-90e7c200-b019-11ea-95f1-03d9f30197b1.png)
![Screenshot_4001](https://user-images.githubusercontent.com/39933493/84852324-c42a5100-b019-11ea-821c-5ab53ef8e784.png)
![Screenshot_4003](https://user-images.githubusercontent.com/39933493/84852325-c4c2e780-b019-11ea-9ecd-05acd6fa2459.png)
![Screenshot (4005)](https://user-images.githubusercontent.com/39933493/84852706-ba551d80-b01a-11ea-95a5-f8b02ee8fcce.png)
![Screenshot (4009)](https://user-images.githubusercontent.com/39933493/84853335-3439d680-b01c-11ea-89de-eb508beb8920.png)
![Screenshot (4007)](https://user-images.githubusercontent.com/39933493/84852826-0acc7b00-b01b-11ea-940c-2c609edb77e9.png)
![Screenshot (4011)](https://user-images.githubusercontent.com/39933493/84853556-aad6d400-b01c-11ea-9efe-682c2e9eba87.png)

The first screenshot shows 2 adventures being started simultaneously with 2 different people. As both of them had different battle timers (2 mins & 5 mins), it caused the cooldown timers to act weirdly, which was fixed after reloading. The second screenshot shows the same user starting 2 adventures (possible due to message lag?), with the third showing the winning outcome/level up messages. Screenshots 4, 5, 6, 7 show more examples of this bug, it seems as we are battling only the second monster during these encounters. I am unsure if Credits/XP is awarded twice. I also have restricted/un-restricted/re-restricted adventurers to one adventure at a time, but that does not seem to have an effect.

**Comment by aikaterna** [comment]
Theoretically https://github.com/aikaterna/gobcog/commit/4fdd83fc33451fddd78f6ff1d076d38734cb9469 will resolve this. I attempted to use max_concurrency instead but that feature wipes out the adventure jump link message. If multiple people spam adventure this should handle that spam long enough for it to calm down, then the jump link message will become available on next command use.
