### ISSUE TITLE
trading a stacked item causes whole stack except 1 to disappear

### ISSUE THREAD

**Issue by jje-ms2soft** [aikaterna/gobcog#196]
![image](https://user-images.githubusercontent.com/11094315/85331492-3bd9ff00-b4a4-11ea-9717-4f1696ea5df7.png)

In the image above, 1x greathelm was traded, What remained was 1x greathelm instead of 4x.
I verified that the other user had only 1x.

Therefor, 3x greathelms disappeared. This appears to be consistently replicatable.

**Comment by aikaterna** [comment]
This is a valid issue.

**Comment by Drapersniper** [comment]
done

**Comment by Drapersniper** [comment]
done
