### ISSUE TITLE
Cart does not obey schedule; is glitched upon arrival

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#201]
The cart came after approx 90 minutes instead of 2 hours.

![image](https://user-images.githubusercontent.com/11650169/85566539-24168e00-b5fe-11ea-91ee-41a793ddada8.png)

![image](https://user-images.githubusercontent.com/11650169/85566564-28db4200-b5fe-11ea-8467-c8b10595fc3d.png)

Also, I saw the cart - it seemed to just start at 30s, and it didn't tick down, then it just disappeared after a short time. Usually it stays something like 3 minutes.

**Comment by Drapersniper** [comment]
The schedule set by you takes place on the next loop. So what you shown above doesn't seem to be valid.

You are saying that the cart timer starts stuck at 30 seconds once it reaches it and gets deleted after 3 minutes?

**Comment by Leperkawn** [comment]
It seemed to spawn at 30 second timer, and didn't update the countdown. Closing issue
