### ISSUE TITLE
Similar item names not defined properly via item picker

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#205]
If you select (1), it gives you a message to be more specific. One name is a subset of the other name.

![image](https://user-images.githubusercontent.com/11650169/85648573-0b928c00-b66f-11ea-8d8a-b928408b6132.png)

**Comment by Leperkawn** [comment]
Same issue
![image](https://user-images.githubusercontent.com/11650169/85649510-51e8ea80-b671-11ea-8b20-fc4e49b9545e.png)

**Comment by Drapersniper** [comment]
done
