### ISSUE TITLE
Negative XP and Credits

### ISSUE THREAD

**Issue by LordChanning** [aikaterna/gobcog#207]
![Screenshot (4024)](https://user-images.githubusercontent.com/39933493/85753079-2c87cb00-b6c9-11ea-845e-29594eebf436.png)

Still have to confirm if it's a visual or actual negative

**Comment by Drapersniper** [comment]
@LordChanning  Can you post the character sheet for all 3 members please

**Comment by LordChanning** [comment]
![Screenshot (4028)](https://user-images.githubusercontent.com/39933493/85754173-1af2f300-b6ca-11ea-9f22-e28403831aca.png)
![Screenshot (4029)](https://user-images.githubusercontent.com/39933493/85754179-1af2f300-b6ca-11ea-95eb-02a6df11cecc.png)
![Screenshot (4030)](https://user-images.githubusercontent.com/39933493/85754182-1b8b8980-b6ca-11ea-9816-caf4ff3bc622.png)
