### ISSUE TITLE
Consolidate levelup messages

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#210]
Leveling up is sent per user at the moment. Needs to be condensed into one page/paginated pages or similar to reduce message send spam and hitting ratelimits for sending.

**Comment by deXxterlab97** [comment]
Maybe petting too? Have it edit to a single message/quote block to reduce spam if people are taming a lot

**Comment by Drapersniper** [comment]
pet commands can happen in DMs. so Not in favour of the Pet commands being consolidated.

Level and rebirth message have been consolidated
