### ISSUE TITLE
A user receive 0 xp from winning nega verse

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#211]
![noxpnega](https://user-images.githubusercontent.com/31835797/85794511-6eebef00-b73f-11ea-97a4-4ac626198f5f.png)

**Comment by deXxterlab97** [comment]
![Screenshot_20200626-001053_Discord](https://user-images.githubusercontent.com/31835797/85795801-8d52ea00-b741-11ea-955e-da2c597ba936.jpg)
added a char sheet for said player

**Comment by deXxterlab97** [comment]
User ID: 259907154721374209

Said user defeated a dragon before (attrib = fat)

![Screenshot_20200626-001401_Discord](https://user-images.githubusercontent.com/31835797/85796072-fa667f80-b741-11ea-8922-1b1d2252c670.jpg)
The proceeds to do the command shown in the first pic. Did not receive level up or use skills of any sort

**Comment by aikaterna** [comment]
Please update the cog, should be fixed in the latest commit.
