### ISSUE TITLE
Users recieving zero credits or xp

### ISSUE THREAD

**Issue by sirenondine** [aikaterna/gobcog#212]
after commit #209 users only receive chests as rewards. no xp or cp are given. Unsure if this is related to #211 or #207

**Comment by sirenondine** [comment]
![0glitbug](https://user-images.githubusercontent.com/50174839/85803503-e6ecf180-b70c-11ea-8927-4c290de91717.PNG)

**Comment by aikaterna** [comment]
Please update the cog, should be fixed in the latest commit.
