### ISSUE TITLE
Players can end up in more than one action group if reactions are spammed

### ISSUE THREAD

**Issue by MeatyChunks** [aikaterna/gobcog#22]
Something to do with being rate limited I guess? Probably need to remove dupes when generating the results.

Todd Burgundy's prayer called upon the mighty Asian Andy to help you. (+60:dagger:/+0:speech_left:)
NitroDubbbz's prayers went unanswered.
Attack Party: | AnonymousChris: :game_die:(18) +:dagger:44 | | Not Lakey. :knife:: :game_die:(6) +:boom::anger_right:️15 +:dagger:30 | | Todd Burgundy: :game_die:(18) +:boom::anger_right:️14 +:dagger:50 | | NitroDubbbz: :game_die:(9) +:boom::anger_right:️12 +:dagger:61 | | :relieved: (Lil Humble): :game_die:(17) +:boom::anger_right:️12 +:dagger:33 | | XXX: :game_die:(6) +:dagger:52 |

**Comment by Drapersniper** [comment]
Fixed in #79

**Comment by aikaterna** [comment]
Theoretically resolved with 1611c0c, please leave an issue with repro steps if you run into this again.
