### ISSUE TITLE
some set bonuses became negative

### ISSUE THREAD

**Issue by RED541** [aikaterna/gobcog#220]
![20200701_091602](https://user-images.githubusercontent.com/63307439/86214961-39e6fe80-bb7c-11ea-9e68-e491a1ae06d1.jpg)
some set bonuses became negative, is it actually just a bug with the [p]setinfo command or did they really became negative bonuses?

**Comment by aikaterna** [comment]
While equipping this set you have 0% increase to your stats (stat values stay as is), your xp gained is halved (-50% less than normal) and you gain 0 currency (-100% less than normal). This display is accurate.
