### ISSUE TITLE
Verify set item count on aleaderboard command

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#222]
See https://discordapp.com/channels/133049272517001216/133251234164375552/729062178891628646 for context.

**Comment by Drapersniper** [comment]
I mean. the command checks for both the equipped and in backpack items.

can they show a screenshot of all their set items and equipped and outut of `aleaberboard` showing them.

`[p]backack set`  > show screenshot if all pages.
`[p]stats`  > show screenshot of  gear page
`[p]aleaderboard` > show screenshot of their entry showing how many items they have.

I don't see any indication the code may be doing something inccorectly here.
