### ISSUE TITLE
Equipping a weapon that you have 3 of produces a visual? bug

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#224]
Replicate:
Have 3 of these crossbows.
Equip 1.
You will now "have 2" equipped.
You will now have 2 unequipped.
Unequip crossbow.
You will still have 3 unequipped.

![image](https://user-images.githubusercontent.com/11650169/86600821-924c4080-bf6e-11ea-95b3-5ce3f72a5a98.png)

![image](https://user-images.githubusercontent.com/11650169/86600836-99734e80-bf6e-11ea-9012-6e6e9c49d7ce.png)

![image](https://user-images.githubusercontent.com/11650169/86600857-9f692f80-bf6e-11ea-8903-91fce0ab9ee6.png)

![image](https://user-images.githubusercontent.com/11650169/86600987-ca538380-bf6e-11ea-8602-e86146a5d8dd.png)

![image](https://user-images.githubusercontent.com/11650169/86601033-d5a6af00-bf6e-11ea-8073-c3cd42c2071b.png)

**Comment by Drapersniper** [comment]
Its not a visual bug... its art of something that was introduced in a more recent pr.

I will just be removing the number owned, from `[p]stats` and it will fix this.
