### ISSUE TITLE
[Request] Lock items from being ever sold

### ISSUE THREAD

**Issue by cry8wolf9** [aikaterna/gobcog#227]
Lock items from being ever sold
A feature, perhaps [p]lock item-name that would lock the item from being sold in a [p]backpack sellall command.
This can allow keeping certain good common items (for example, 2-handed weapons with att/int of 10+) while being able to sell other items. Likewise, this can be used to keep items in any tier while allowing you to more easily manage your inventory

**Comment by aikaterna** [comment]
Pin methods were requested in #72. Notifications about that feature being added will be posted in that issue.
