### ISSUE TITLE
[Suggestion] alternate handling of rage/focus etc

### ISSUE THREAD

**Issue by KingPin** [aikaterna/gobcog#234]
A bunch of people using the rage/focus commands spams the channel after the adventure command and sometimes pushes the adventure post off the page.

One possible solution is to not allow manual rage/focus command but rather use the other stats (possible luck? or attack for berserker and Int for a wizard) to random cast the rage/focus skills. i.e. on every attack/magic cast, rng cast rage or focus instead fo allowing manual invocation. this will use our stats more, and give them more meaning and also reduce clutter in chat.

thanx :)

**Comment by Drapersniper** [comment]
Could open up the command to be run in DMS.

But no I don't agree with what you said about removing the skills and adding an RNG dependency to it.

You could make a room in your server to allow only skills to be used there for the time being.

**Comment by Drapersniper** [comment]
Fixed by allowing commands in DM.

In the future its up to you to better manage your server and restrict commands in rooms you dont want them run in
