### ISSUE TITLE
Trade command does not recognize 'reforged mithril sabatons' (Possible shared text in item name issue)

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#235]
The trade command cannot see this item, possibly due to my other sabatons. This feature (correct item distinction with similar names) was working until just now it seems.

The top part of the screenshot is AbsolutelyNotLep's backpack.

![image](https://user-images.githubusercontent.com/11650169/86979586-b6b34300-c14f-11ea-982a-fccba1aaa0d2.png)

**Comment by Leperkawn** [comment]
Here is another instance, with shared name 'battleplate'
![image](https://user-images.githubusercontent.com/11650169/86979886-65f01a00-c150-11ea-9679-3dd68d8db4e0.png)

**Comment by Drapersniper** [comment]
Out of curiosity.... do you have one instance of this item equipped when trying to trade the other versions ? I think I may have introduced a bug if that's the case.

**Comment by Drapersniper** [comment]
And does it work if you use the full name (markdown)

**Comment by Leperkawn** [comment]
AbsolutelyNotLep does have the Savage Silver Battleplate equipped, as well as the reforged mithril sabatons. Good catch.

**Comment by Leperkawn** [comment]
> And does it work if you use the full name (markdown)

I might be misunderstanding this but i cannot replicate
![image](https://user-images.githubusercontent.com/11650169/87044479-907bba80-c1c4-11ea-97b8-b04dd3bc0701.png)

**Comment by Drapersniper** [comment]
yeaaaah i think its a regression i introduced.  its filtering out equipped items.

It's an easy fix I will try to get it out later today.

**Comment by Drapersniper** [comment]
In fact ... Fixed
https://github.com/aikaterna/gobcog/pull/240
