### ISSUE TITLE
Can't catch pets

### ISSUE THREAD

**Issue by Kuodos** [aikaterna/gobcog#238]
My stats are ATT 16/ CHA 18/ INT 21/ DEX 16/ LCK 15 for a total dipl_value of 18+21//3+15//2=**32**, i tried to catch a pet (blue moth, **cha 0**, no req) with a roll of 40, but the moth escaped. If I understand the code correctly, I should've caught it.

**Comment by Drapersniper** [comment]
Catches are not guaranteed. meeting the requirement allows you a chance at catching.

**Comment by Kuodos** [comment]
I tried to tame a pet 104 times already and had no luck. I don't think that ranger should work like that, pet is ranger's main class feature

**Comment by Kuodos** [comment]
ok nvm catched other moth on 109th try
