### ISSUE TITLE
Backpack delta view ([p]backpack t) shows 2handed weapon stats halved for equipped weapon

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#239]
2 handed weapon stats are typically doubled from their raw value, and the `[p]backpack t` uses their "one handed" raw stats for your equipped weapon.

**Comment by Drapersniper** [comment]
Can you please show the screenshot.

This should not be the case.

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/87046559-44933a80-c1f1-11ea-96b5-fe000b735e58.png)
For context this is what the delta view will do for weapons.

**Comment by Drapersniper** [comment]
HAHAHAHAHAHA ....
By any chance did you not have anything equipped?

**Comment by Leperkawn** [comment]
![image](https://user-images.githubusercontent.com/11650169/87048576-de46f180-c1c9-11ea-8290-709fd6f5e899.png)
Difference in filtered version vs not filtered

**Comment by Leperkawn** [comment]
I did have items equipped already, yes.
