### ISSUE TITLE
[Request] Auto-sell all non-legendary, non-set gear upon rebirth

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#243]
This could or could not include equipped stuff. Users should be doing this anyway before rebirthing, so it is a bit of a QOL enhancement.

**Comment by aikaterna** [comment]
Automation requests are not really something I'm interested in in a general sense. You can run [p]backpack sellall if you would like this functionality.

**Comment by Leperkawn** [comment]
Does backpack sellall ignore set? if so, then thats good. I've just always been afraid to run it.
