### ISSUE TITLE
Guardians of nazarick auto release

### ISSUE THREAD

**Issue by YumYumYumiko** [aikaterna/gobcog#246]
Guardians of nazarick even after being caught gets auto released if any of ainz ooal gown items are unequipped, which makes catching it useless as ainz ooal gown has 0 xp mult and having that we can't lvl up, the extra credits are useless as well since we can't pvp. I don't think it should be auto released if we unequip ainz ooal gown items as the other requirement ( 1 million charisma) is almost impossible with the current rebirth system.

**Comment by Drapersniper** [comment]
If you no longer have the requirement to keep the pet it will be auto released.

Nothing will be changing here.
