### ISSUE TITLE
[Question] How to figure out your total damage?

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#247]
![image](https://user-images.githubusercontent.com/11650169/87446352-2e0d2a80-c5c7-11ea-815d-430c491f621c.png)
Based on my investigation it does not appear that your damage is the result of the middle number + the final number. How the addition of each section works, including the dice roll, is not clear to me either (Referring to the "+"'s used)

I am curious how to calculate your final damage as this is important to know if your various builds or strategies are effective on an individual level

**Comment by Drapersniper** [comment]
Those numbers are accurate issue here is that you don't get a total once monster resistencies are taken into account, that could be changed though however it would more often than not result in a slightly lower than normal damage if done so.

**Comment by Leperkawn** [comment]
Ok, so a modifier is placed on the result of the dice roll which gives a different final result. However it sounds like if you add all 3 numbers shown you get your "base" damage.

One interesting point is that it does not seem like the Cleric scales very well when playing with a group of 5-7 people (Rebirth ~6). I have more information about this if you are curious. You also cannot see the cleric's dice roll so its unknown how good their rolls are.

**Comment by Leperkawn** [comment]
Regarding the cleric thing, i think my conclusion is that the class can only consistently produce damage similar to the Beserker/Wizard if there is more than ~5 non-clerics fighting. This is further backed up by the fact that the Cleric is falling behind in XP, due to outputting ~50% or so damage of the other classes.

This is anecdotal, there are lots of things at play including stats. I am not making any claims to the game being broken so please don't take them as such. I am just making an observation that may or may not be actionable on your guys's end.

Here are the stats if you are curious. Damage output is roughly ~50% of similar rebirth level/stats Wizard or Beserker. Blesses with good rolls are stronger than rage/focus FWIW though.

```
{Rebirths: 6, 
 Max Level: 50}

A level 45 Cleric

Clerics can bless the entire group when praying.
Use the bless command when fighting in an adventure. 

- ATTACK: 84 [+0] - CHARISMA: 86 [+0] - INTELLIGENCE: 102 [+22]

 - DEXTERITY: 73 - LUCK: 98 
```

**Comment by Leperkawn** [comment]
I think this issue can be closed
