### ISSUE TITLE
[Request] Ability to show only equippable gear in backpack (with deltas)

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#248]
Ideally you can combine with the delta-gear flag (t). It would be cool to do `[p]backpack te` or `[p]backpack t e` etc. That way you can view all the equippable gear in a delta view, easily seeing what new gear you are able to put on.

**Comment by Drapersniper** [comment]
Sorry but not via flag.

currently the backpack command already has no many variations, I'm not opposed to this however if anything it will be a new command.

**Comment by Leperkawn** [comment]
No problem! The flag was just a suggestion. I will update it.

**Comment by tmoze315** [comment]
This would be a really handy QOL improvement 👍 

How about something like `-ebackpack` (for equipable backpack)?

Supporting the comparison flag would make gear equipping SO much easier (i.e. `-ebackpack true`)
