### ISSUE TITLE
Unequip slot does not work

### ISSUE THREAD

**Issue by Suven-p** [aikaterna/gobcog#250]
Using _[p]unequip slot_ does not work in most cases since _ItemConvertor_ class raises _BadArgument_ and exits before entering function _unequip_. 
It does work in some cases for example if equipped item is **Reforged Runite Necklace** then _[p]unequip neck_ does work but its probably due to partial name match.

**Comment by Drapersniper** [comment]
Note to self: Do we want this? if so  the concerter should be redesigned.

Inclined to say no we don't want this to keep the logic from getting more complex and avoiding conflicts.

**Comment by Suven-p** [comment]
There's already if statement to handle case for slot and the docstring says: 
Use `[p]unequip name of item` or `[p]unequip slot`

I haven't tested it out but using `itemconvertor` inside the function instead of function annotation would fix the problem. It would still throw an exception but try/except conditional can handle that.
This is itemconvertor used in forge:
`item = await ItemConverter().convert(new_ctx, reply.content)`
