### ISSUE TITLE
Max Forge cooldown missing a set of parentheses

### ISSUE THREAD

**Issue by songdavid98** [aikaterna/gobcog#251]
In adventure.py line 2640, your code seems to double the difference (doing subtraction first) instead of doubling the sum of your stats. This makes it so that your forge cooldown with low stats is nearly 2 hours, when I think the intention is to cap it at 1 hour.

Upon comparing the code from the other cooldowns, it seems that they have an extra set of parentheses to prevent this issue, but the forge cooldown seems to be missing that extra set of parentheses.

line 2640
cooldown_time = max(900, (3600 - (c.luck + c.total_int) * 2))

fix to: 
cooldown_time = max(900, (3600 - ((c.luck + c.total_int) * 2)))

note the triple parentheses behind the 2, as is seen in the cooldown times for bless and rage

**Comment by Drapersniper** [comment]
Nope there's no intention to cap it at 1 hour here.
