### ISSUE TITLE
[Request] Backpack sell items above/below a given level

### ISSUE THREAD

**Issue by tmoze315** [aikaterna/gobcog#256]
I often don't want to sell all items of a given rarity(e.g. legendary) as they can still include items that I can equip in a few rebirths time.

Are we able to get a new command that lets you sell items below/above a certain level (please).

For example:

`-backpack sellallbelow 40` or `-backpack sellall below 40`

`-backpack sellallabove 200` or `-backpack sellall above 200`

**Comment by Drapersniper** [comment]
Im not in favour of this feature.

**Comment by aikaterna** [comment]
The highlighting showing whether an item is equippable or not is probably the farthest we'll go on this (RIP mobile users). The intent here is not to deny features that people want, but as an overall design point for the game I want people to be involved with managing their items and a quick sellall of things in bulk while specifying conditions is not really something I want to see automated.
