### ISSUE TITLE
[Request] Improve rebirth experience

### ISSUE THREAD

**Issue by tmoze315** [aikaterna/gobcog#257]
Rebirth removes all of your equipment and loot boxes. The most optimal thing to do is:
- Open all loot boxes
- Unequip all your items
- Sell all items (excluding legendary and sets) for $
- Transfer your bank balance to another player
- Rebirth
- Get your bank transferred back to you

This process is quite arduous and unnecessary I think. I suggest rebirth working something like this

- Will unequip your current equipment 
- Sells all normal, rare and epic items. (Even if it has like a ~10% $ reduction, for convenience)
- Keeps your bank balance

I think this will help a lot, especially for the first 60-70 levels where rebirthing is very frequent.

Alternatively, a wallet & bank system could help you manage your money without the need for another player. Loosely I'm thinking:
- The current bank becomes the "wallet". All wins/losses, costs etc are taken from your wallet
- You lose your wallet balance on rebirth
- You have a new "bank" which stores your money and is protected against losses and rebirths
- You can transfer a fixed amount into your bank x times a day (e.g. on a 8h cooldown
- You can withdraw from your bank as many times as you want (maybe on a 1h cooldown?)

Thoughts?

**Comment by Drapersniper** [comment]
Automated selling of items is a no from me.
Keeps your bank balance is also a no from me.


the idea of the wallet is interesting though, could see some sort of werehouse for items being a good mechanic.

**Comment by tmoze315** [comment]
Okay no worries. Being able to store items in a warehouse too would be awesome 👍

**Comment by Drapersniper** [comment]
Fwiw transferring the the currency to another player is not something that's intended, but since you flagged that up.... thanks I'll make sure that's not feasible anymore.
