### ISSUE TITLE
Bug: Backpack shows as all teal

### ISSUE THREAD

**Issue by Leperkawn** [aikaterna/gobcog#261]
Seems to change right after the first single `'` in the top row

![image](https://user-images.githubusercontent.com/11650169/88435871-202e8500-cdd1-11ea-87ff-54440da9e6be.png)

**Comment by Drapersniper** [comment]
Just FYI, this is a bug with discord.

We sort her have to wait for it to be fixed or disallow all special characters from everywhere to ensure it is fixed everywhere

**Comment by aikaterna** [comment]
Hi, a temp fix is in f40366e till Discord fixes their css rendering.
