### ISSUE TITLE
Cannot trade with other user with same rebirths

### ISSUE THREAD

**Issue by sirenondine** [aikaterna/gobcog#263]
![Screenshot from 2020-07-26 23 27 01](https://user-images.githubusercontent.com/50174839/88503804-671aa700-cf98-11ea-91ee-b6673cb99770.png)
![Screenshot from 2020-07-26 23 26 30](https://user-images.githubusercontent.com/50174839/88503808-697d0100-cf98-11ea-9059-2fb8766a9917.png)

I'm not sure if this is intentional or if I am missing something.

**Comment by songdavid98** [comment]
I assume that the logic behind the bot message is that you don't high rebirthers selling low rebirthers OP equipment, but it is OK for low rebirthers to sell to high rebirthers.

If that's the case, then there's a mathematical error on line 1466.
The code's logic doesn't match the bot message
If the bot's message contains the correct intention, then the line should be

`if buy_user.rebirths +1 < c.rebirths:`

**Comment by sirenondine** [comment]
In this case they are both at the same 1 rebirths.
