### ISSUE TITLE
Show only items from specific set

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#264]
You can sort to show only set items, or only set items with head slot. How about show only specific set which helps a lot in managing sets to see which item you're missing. Example I want to show only ainz of ooal goawn items

**Comment by Drapersniper** [comment]
No to backpack... but maybe to setinfo... dunno how I feel about it yet, don't wanna make the game to mindless when it comes to item management that you just pick the best item you have and get rid of the rest with one command
