### ISSUE TITLE
transfer inconsistency?

### ISSUE THREAD

**Issue by sirenondine** [aikaterna/gobcog#273]
![Screenshot from 2020-07-29 15-31-49](https://user-images.githubusercontent.com/50174839/88850290-c521d700-d1b0-11ea-8c0e-e2a9e9de7e82.png)
I'm unsure if this is a bug or just the way it is. I have it set to 1 credit = 3 gold. when transferring back and forth the rate can cause a loss. Could call it a transfer tax I suppose :smile:

**Comment by Drapersniper** [comment]
I should have documented it better, so when you set the value with rate command, the withdraw value is 90% of that. So it's never a 1-1

**Comment by Drapersniper** [comment]
So although not an issue, I'm happy to make that configurable if yall feel it's necessary.

**Comment by sirenondine** [comment]
ah that makes sense then. Thanks.

**Comment by sirenondine** [comment]
could be a cool feature to have

**Comment by Drapersniper** [comment]
Won't do it tonight, but on my next pr I'll add a configuration for it.

**Comment by Drapersniper** [comment]
Just so you two know, this hasn't been added as a new command. 

`[p]adventureset economy rate` accepts 2 numbers now.


The help text for it explains it, hopefully it covers all your needs, if you wanna be able to reach me with filling issues please head over to <discord.gg/KcAbsvD> always open for a convo about adventure, or early reporting things/suggestions. haven't seen you around (so saying it just in case)
