### ISSUE TITLE
[Adventure] Devreset Skill Points

### ISSUE THREAD

**Issue by Menteroth** [aikaterna/gobcog#276]
To quote yourself from the Discord:
```testing path is to take a user that has played organically through the game system, note their stats, run devrebirth on them, maybe once to set them to some level and then to set them back to its original level and see if the baked-in stat point values are the same```

I asked about a dev command to add skill points, because I thought my skill points weren't added to my Attack stat because it was showing `+[0]`. But can also be that I didn't add my items with the same stats that I had before reset. I am not entirely sure.
So just adding this just in case it needs to be looked into.

**Comment by aikaterna** [comment]
![image](https://user-images.githubusercontent.com/20862007/88873100-bfd48480-d1d0-11ea-9ea6-56349fefd8bd.png)
User has +1 atk in the first stats panel and none after the devrebirth

**Comment by Menteroth** [comment]
Just remember this thing. Skill points are still not added when you devrebirth. 
Also, I'm just testing this on my alt. account. So not using with proper characters, except for first time on my own one by mistake.

The test character was Rebirth 1 and level 5. I did `devrebirth 1 5 Coin`
Before reset it had `ATTACK: 0 [+2]` and after reset it's `ATTACK: 0 [+0]`

**Comment by Menteroth** [comment]
My bad. I didn't notice the unspent skill points after reset. I was thinking they would be added as bonus to the same stat after reset and not points to be used again.
![image](https://user-images.githubusercontent.com/24851042/93711894-20899900-fb52-11ea-9435-fc178fad21ca.png)

**Comment by Menteroth** [comment]
I forgot to ask if there will be anything added to add skill points manually in the future or if I'm just going to have to use a generated item where I have added those 9 points on top of the actual item I copy stats from so they aren't lost?
