### ISSUE TITLE
[Suggestion] For New Players

### ISSUE THREAD

**Issue by Menteroth** [aikaterna/gobcog#283]
Maybe add a text where it says they can use `apayday` command to gather some gold?

I feel like people jumping into a channel where an adventure is going on that also don't know what it is have no clue how to join when they don't have enough gold and how to get some.
![image](https://user-images.githubusercontent.com/24851042/89443819-1e5dad80-d751-11ea-8d64-387d63193466.png)

**Comment by Drapersniper** [comment]
Good spot,
note to self:
Check wether split economy is enable if it is state so on DM, and `[p]adventure` commands.
