### ISSUE TITLE
[Command Bug] 

### ISSUE THREAD

**Issue by LadyShix** [aikaterna/gobcog#284]
![IMG_20200806_133134](https://user-images.githubusercontent.com/69292684/89495530-0aff2080-d7eb-11ea-8855-774d3b11397a.JPG)
![IMG_20200806_133148](https://user-images.githubusercontent.com/69292684/89495553-15b9b580-d7eb-11ea-982b-0f2130fa0fd7.JPG)

## Complete these first
- [   ] I confirm that I am the owner of the bot running Adventure.
- [ / ] I confirm that I have not modified the source code of Adventure.
- [ / ] I'm an Adventure user but not the bot owner.
- [ / ] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Command name

c!adventure 

## Expected Behavior

Should initiate adventure.

## Current Behavior

Adventure Version - 3.3.4

Whenever the c!adventure command is used, the bot says that there is an on-going adventure with a Bronze Guardian. That adventure has culminated over eleven hours ago. There are also some players whom the bot doesn't give a response to at all.

## Possible Solution

A restart may help.

## Context (Environment)

Since the command is broken, we have been unable to use it in our server and has since been unable to play. We would like to be able to play again.

The c!adventure command is broken. It does not initiate adventures like it is supposed to.

**Comment by aikaterna** [comment]
Have a server admin or mod run the `adventureset locks adventure` command and it will be resolved.
