### ISSUE TITLE
[Feature Request] backpack sellall legendary -degrade 0 / More prefix, suffix, materials

### ISSUE THREAD

**Issue by songdavid98** [aikaterna/gobcog#287]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [x] Command
- [x] Functionality

## Describe your requested feature

Command: backpack sellall legendary -degrade 0 
As you rebirth more and more, players accumulate more and more legendary equipment. Unless you decide to sell all your legendaries at some point, players will have to decide between selling degrade 0 legendaries one by one, or give up on selling.
A command that lets you further filter legendaries by degrade for selling would be a nice QoL change for higher rebirth players.

Functionality: More prefix, suffix, materials
Generally, I have found that there seems to be a cap on normal equipment, usually maxing out at Blessed Unknown equipment of Adventure, which results in lvl 185 ish equipment. There is a wall past that. So players whose levels are higher than that don't really have fitting equipment for their level (aside from the AOG set), so I'm suggesting a few more adjectives that might help.

Most of them don't need to be better than the pre-existing ones. Also, I'm going to include some modern-sounding ones, but it's alright if you don't like them. 

Materials: platinum, steel, diamond-studded, ruby, sapphire, emerald, carbon-fiber, wooden

Prefixes: godly, ultimate, fancy (char), comfortable (dex), barbaric (att), strange (int), 

I feel like there aren't any high stat values in suffixes
Suffixes: destiny / fate, champions, conquerors, wisdom, strength, voices, fortuity, skill

**Comment by Drapersniper** [comment]
I love everything here, but one think I consistently will shut down is the ability to sell items by degrade level.

Item degradation is supposed to be a mechanic, the number got exposed due to player demand but I'm not okay adding a command that basically makes that mechanic pointless as it just becomes something that you run 1 command before you rebirth.

**Comment by Drapersniper** [comment]
I do wanna think of some other ways to make the item management more engaging because I know at higher level the intake of items is much larger than at lower levels

**Comment by songdavid98** [comment]
I suggested to suven prior to all this, to make a backpackfinditem -r legendary -deg 0 command, which he did. It listed all the degrade 0 items, which I still had to sell 1 by 1. I don’t know if that’s what you mean by more engaging, but I'm just throwing an idea out there. 

I will comment that rebirthing already is a slog with all the commands you need to do. There is opening all the normal, rare, epic, legendary, and set chests. Then unequipping everything you have. Then selling all the normal, rare, and epics. Then selling all the degrade 0 equipment, which is basically impossible on mobile, and a copy paste routine on pc that dwarfs the amount of time spent on the rest of the commands. 

I'm ok with running the 9 commands (5 for chests, 1 for unequip, 3 for selling) before rebirth, but the selling of degrade 0 can easily take over an hour, even with my glorious ctrl-C windows-V skills on PC. 

I can tell you that some new adventure players were scared off by all the commands they had to learn to go through with the rebirth process. 

I know that less interaction seems to be something you don’t want, but the amount of interaction for rebirthing is already turning some new players off. 

Unrelated comment: it looks like you went through with my suggestion here https://github.com/aikaterna/gobcog/issues/265 
Did you realize the 0.01 was a bug?

**Comment by Drapersniper** [comment]
so the 0.01 wasn't a bug, the `max()` was a bug, but because its there for a while now didnt want to give clerics a super nerf.

thanks for spotting the ascended items ... completely forgot about forging.

the idea of item management is to do so while you are playing the game not just before you rebirth.

There is no command you MUST run before rebirthing. all you need to run is `[p]rebirth` everything else is optional.
