### ISSUE TITLE
Balancing Clerics and KoM and King TItan

### ISSUE THREAD

**Issue by songdavid98** [aikaterna/gobcog#296]
Pray with bless got a little too strong.

I noticed the changes were 
c.rebirths -> rebirths
and 0.01 -> 0.1

The root is this previously-unused line of code: `rebirths = c.rebirths * (3 if c.heroclass["name"] == "Cleric" else 1)` , which triples the rebirth growth scaling.

The code right now: 
`pray_att_bonus = int(
                            (mod * len(fight_list)) + ((mod * len(fight_list)) * max(rebirths * 0.1, 1.5))
                        )`

I have a few ideas on how to balance the base amount and the growth rate and the base amount for praying with bless.

Prior, clerics were doing 2.5 * roll damage per player with virtually no scaling. Meaning, rb15 clerics were doing up to 125 damage per player, and pre-rb15 clerics were doing up to 50 damage per player. 

Currently, as a rb19 player, I'm doing 6.7 * roll damage per player, doing up to 335 damage per player, which is OP.
A rb15 player would be doing 5.5 * roll damage per player, doing 275 damage per player. Mind you, this is regardless of stats, just rebirth (meaning that a rb15 lv 1 cleric is comparable to a rb15 lv 125 cleric. Due to the luck stat, it's actually about half as strong, which is extreme compared to the power strength of the other classes at lv 1).

I'm suggesting the pray bonus be calculated like so: 

`pray_att_bonus = int(
                            (mod * len(fight_list)) * ( c.rebirths * c.luck * 0.0005 + 1 )
                        )`
I think this is very fair, and helps makes clerics more similar to other roles where stats matter.

Using this formula, I, as a rb19 cleric with 345 luck will be doing 4.2 * roll damage per player, which is up to 210 damage per player, which I think is very fair.
For a rb15 player with 280 luck, they will be doing up to 155 per player.
We can discuss this further in discord if you like, but this I feel is best. If you want to tweak it, I recommend tweaking the growth factor of 0.0005. 

============================================================

As for the KoM and King Titan:
I understand that the KoM broke the meta, but the changes were too harsh, especially for a set that many people worked hard to get. 
I understand that there are some meme sets in the game, but KoM and King Titan don't need to be among them. There are balanced ways to deal with them. 

The change I recommend is zeroing out all the other stats instead of sending them into the negative. 
There are several reasons why. 

1. Huge credit loss due to bad dex stat when losing a battle
2. Griefing (deliberately using the negative stat to lose)
3. Huge credit loss due to negative luck stat when WINNING a battle
4. Lower than normal xp gain due to negative int stat

Note: You probably copied the xp multiplier from KoM to King Titan, but the xp gain isn't really equal, since the bonus int from KoM counters that xp multiplier. I'd just set the xp multiplier back to normal for King Titan.

**Comment by Drapersniper** [comment]
KOM and KOT, already going to be rebalanced as part of 3.4.0
