### ISSUE TITLE
[Feature Request] Small chance for chests on rebirth

### ISSUE THREAD

**Issue by tmoze315** [aikaterna/gobcog#301]
# Feature request

## Complete these first

- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting

- [ ] Command
- [x] Functionality

## Describe your requested feature

When rebirthing, it wipes all of gold, chests, equipment (<=epic). You trade this for slightly higher base stats and a higher max level.

My request is to also give you a small chance to loot legendary or set boxes after a rebirth. Your chances could be increased based on how much money you're losing rebirthing (e.g. each 1mil gives you +1% chance of getting a set chest, capping out at 10%).

I think it would add an immediate reward to rebirthing that feels more rewarding that just losing everything. Also gives a little more incentive to stay at max level to get more gold and increase odds of a drop - which helps others on the server.

I'm thinking that worse case, you always get 1 legendary chest when you rebirth. This _could_ start after x rebirths (e.g. 10) too so it doesn't get too unbalanced. But you have a chance to loot more based on your amount of gold (which effectively increases your max roll, similar to how negaverse works).

So, it's like a mini negaverse on rebirth that gets you chests rather than XP.  The amount of set chest drops can be balanced based on what you devs feel is best. But an additional set chest every 3 rebirths sounds fair on average?

This would be something that happens as part of -rebirth and your loot is available to open after rebirthing finishes.

**Comment by Drapersniper** [comment]
This is a complete hard no from me:
>  set boxes after a rebirth.
> I'm thinking that worse case, you always get 1 legendary chest when you rebirth

> This would be something that happens as part of -rebirth and your loot is available to open after rebirthing finishes.
This is already something that happens in game.
