### ISSUE TITLE
[Feature Request]  Add missing info to `adventuresettings`

### ISSUE THREAD

**Issue by Drapersniper** [aikaterna/gobcog#302]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [x] Command
- [ ] Functionality

## Describe your requested feature

- Add Economy settings
- Add Tax brackets
- Add Easy mode (3.4.0 dependant)

**Comment by aikaterna** [comment]
add display to show current day bonus and/or entire week bonuses
