### ISSUE TITLE
[Bug] Set Bonuses

### ISSUE THREAD

**Issue by LordChanning** [aikaterna/gobcog#311]
## Complete these first
- [x ] I confirm that I am the owner of the bot running Adventure.
- [x ] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [x ] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior

Multipart set bonuses apply as shown in !setinfo

## Current Behavior

3.4.2 

For The King of Mages
1) Att and Cha is negative despite 9 part bonus showing a positive
2) 70% stat bonus when it should be 30%
3) -75% xp when it should be -25%

I believe that something similar to this is affecting all sets that have a multi part bonus. The ones with only 1 set of bonuses seem to work properly. 

## Possible Solution

N/A

## Steps to Reproduce

1. Look up set bonus using setinfo
2. Equip a multi part bonus set
3. Look at stats page

## Context (Environment)

This bug causes confusion as the bonus on setinfo is not accurately represented when equipped

## Detailed Description

Set bonuses in setinfo apply properly when in stats

## Possible Implementation

This is my personal theory that isn't fully tested out, it seems the bonuses are 'adding' together. 

In my TKOM example, 

{"parts": 3, "att": -3000, "cha": -3000, "int": 0, "dex": -50, "luck": -50, "statmult": 1.1, "xpmult": 0.75, "cpmult": 1.0},
{"parts": 6, "att": -3000, "cha": -3000, "int": 0, "dex": -50, "luck": -50, "statmult": 1.3, "xpmult": 0.75, "cpmult": 1.0},
{"parts": 9, "att": 3000, "cha": 3000, "int": 0, "dex": 50, "luck": 50, "statmult": 1.3, "xpmult": 0.75, "cpmult": 1.0}

This causes a -3000 on att and cha, a 70% stat boost and -75% xp

**Comment by Drapersniper** [comment]
I don't know what you are trying to say here. The part bonuses are supposed to be additive
