### ISSUE TITLE
[Feature Request] Rebalance how money were gained/loss like before (especially for low level players)

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#314]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [ ] Command
- [x] Functionality

## Describe your requested feature

The party consist of people who are under 10 rebirths, so they are fairly new. But it's still a party of people. 

After the 3.4.2 update, people have noticed they are losing way more money than usual. It's important because the money gained back (and the XP) is significantly smaller too. Given the fact that it's a new group, we only starting to face ascended monsters with dragons (non asc) and transcended sometimes. The problem here is we don't always win against ascended monsters unless its Health/Talk point were small and we have enough cooldown going in the battle.

This made progression to newer level extremely difficult. People are reporting that they gain not enough money from adventure (lose more than they win) and with default of gaining 250 currency every 2 minutes (or whatever is set by the bot owner) it's sadly the only way to gain significant income in this game, let alone enough to "super-progress" with negaverse.  

The problem did not exist prior to 3.4.2 update as pointed out by some users.

If needed, I can provide some screenshot of some of our losses/wins.

**Comment by Drapersniper** [comment]
![image](https://user-images.githubusercontent.com/27962761/91474862-b8b59a80-e892-11ea-8c68-77f63d40e4ae.png)


TL:DR Not changing currency gains,  however 3.4.4 will make it so up to 10 rebirths losses are lower than normal, and XP and loot in hidden mode is higher than default

**Comment by aikaterna** [comment]
Red economy has always been difficult to balance and imo, trends towards the high end if you have a multitude of game cogs installed. A lot of my bot games that I written have some currency draining effect, and this update had what I feel is more realistic numbers applied to the game. Every Red economy ecosystem is different and people have different cogs installed, so my choice here about lessening numbers isn't going to work for everyone.
