### ISSUE TITLE
[Command Bug] [prefix]give item

### ISSUE THREAD

**Issue by eunsah** [aikaterna/gobcog#345]
## Complete these first
- [x] I confirm that I am the owner of the bot running Adventure.
- [x] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Command name

[p]give item
[p]give item @locastan "fine dagger" 1 att 1 charisma -1 degrade 100 level rare twohanded

## Expected Behavior
the flag thats used to set level should effect on the generated item

## Current Behavior
Adventure version: 3.4.3.2
at the time of testing, the level flag does NOT effect the level requirement on the generated item

## Possible Solution
<empty>

## Steps to Reproduce
1. do [p]give item `@user` "item" 100 att 100 diplo 100 int 100 dex 100 luk -1 degrade 1 level normal twohanded
2. check item in backpack [p]backpack
3. item two handed   200   200   200   200   0     748   1     N/A   N/A  
4. the generated items' required level is 748

## Context (Environment)
a level 1 item with high stat as a prize

## Detailed Description
<empty>

## Possible Implementation
<empty>

**Comment by aikaterna** [comment]
Event-class items are the only items where a level can be directly set to override the automatic level determination. Use something like [p]give item `@user` "Fancy Pants" "item" 100 att 100 diplo 100 int 100 dex 100 luck -1 degrade 1 level event twohanded

**Comment by eunsah** [comment]
Understood and thanks for the quick response, following the solution; 
Is it the event flag or the double str() in front that makes it an event class?
And also in that case may i suggest to change the help message corresponding to the correct syntax?
by help message, I am speaking about the message given when entering `[p]give item`

the current message is as following 
---
Event items can have their level requirement and degrade number set via:
N degrade - (Set to -1 to never degrade on rebirths)
N level

>give item @locastan "fine dagger" 1 att 1 charisma -1 degrade 100 level rare twohanded

Again, much appreciated for your explanation

**Comment by aikaterna** [comment]
What makes it an event-class item is when you put the word `event` into the creation string, like where you would put `normal`, `rare`, `epic`... etc.

The help command will stay as is. That section specifies that it is an event item that can have a level req and a degrade number set. 

If you have more questions, please ask in the Red cog server in my channel.
