### ISSUE TITLE
[Feature Request] Text clarity for possible backyard rebirth command

### ISSUE THREAD

**Issue by Melon317** [aikaterna/gobcog#346]
# Feature request

## Complete these first
- [x ] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [x ] Command
- [ ] Functionality

## Describe your requested feature

This request is a follow up to the command that makes backyard rebirth easier and faster. 
Since there is a possibility to fail evolution, which may cause issues when using the command to instantly rebirth, I suggest a function that either:

1. Fails the rebirth, returns all gold spent and restores backyard to previous state. 
2. Fails the rebirth process, stops at the previous successful level, and refunds a portion of the money left. 

I think it is fair to incur a cost even if rebirth fails as the player is using this command to save time at a risk.

**Comment by Drapersniper** [comment]
This is not related to adventure. Adventure does not have a backyard command.

**Comment by Melon317** [comment]
My bad, will post this to the right place.
