### ISSUE TITLE
[Feature Request] rebirth level changing 

### ISSUE THREAD

**Issue by eunsah** [aikaterna/gobcog#349]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [x] Functionality
- [ ] Command

## Describe your requested feature

currently if im not mistaken, after rebirth 10, the max level will be at 75 and with addition of 10
always end on a 5

i am proposing changing it to 0, by either making rebirth 10 also add 5, or add 15

i just think numbers ending with 0 looks better

**Comment by Drapersniper** [comment]
It's not always +5.

**Comment by eunsah** [comment]
reopening the issue with Drapers' solution as a suggestion!

in [adventure/charsheet.py#L802](https://github.com/aikaterna/gobcog/blob/5840f51c22bc3b3afc898a8053099434226cfd1e/adventure/charsheet.py#L802)

it could be 
>     for _loop_counter in range(rebirths):
>           if rebirths >= 20:
>               maxlevel += REBIRTH_STEP
>           elif rebirths > 10:
>               maxlevel += 10
>           elif rebirths <= 10:
>               maxlevel += 5
>           rebirths -= 1
 instead of 
>     for _loop_counter in range(rebirths):
>             if rebirths >= 20:
>                 maxlevel += REBIRTH_STEP
>             elif rebirths >= 10:
>                 maxlevel += 10
>             elif rebirths < 10:
>                 maxlevel += 5
>             rebirths -= 1
