### ISSUE TITLE
[Command Bug] Adventureset easymode toggle is broken

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#360]
## Complete these first
- [x] I confirm that I am the owner of the bot running Adventure.
- [x] I confirm that I have not modified the source code of Adventure. :trollface: 
- [ ] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Command name
adventureset easymode

## Expected Behavior
easymode being off should not show easymode when playing an adventure round

## Current Behavior
3.4.4 (PR)
The game defaults to easymode and is not changeable.

## Steps to Reproduce
Use [p]adventureset easymode
Toggled to easymode
Play an adventure game, it has an image and mob info
Use [p]adventureset easymode
Toggled to easymode off
Play an adventure game... it still has an image and mob info

## Context (Environment)
Needs to be addressed as this is a larger bug

**Comment by Drapersniper** [comment]
Right i think you are seeing https://github.com/aikaterna/gobcog/pull/313/files#diff-9525d6f403a212ad2045f0836e576beb7134c28821ea8ba39d149b385e72a82bR5876

its by design

**Comment by aikaterna** [comment]
Thanks very much for the details on this, wasn't aware of that of course 😃
