### ISSUE TITLE
[Feature Request] Improve psychic class: randomize insight output

### ISSUE THREAD

**Issue by deXxterlab97** [aikaterna/gobcog#365]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [ ] Command
- [x] Functionality

## Describe your requested feature

Randomize the text for Psychic when they're doing insight so that it doesn't always default to show how weak the monster is with sword attack. 

For example the first 3 lines would cycle randomly between showing sword resistance, magic resistance and talk resistance

That way, we could have some more variety in predicting what to do (talk or attack) with the monster.

**Comment by aikaterna** [comment]
Psychic insight is a roll, and the roll determines what you see in the text window. If you roll really well, you will see all the resistances, info about the mob, etc. If you roll fair, it might show you one random stat info like atk, or magic, or other. If your roll sucks you get nothing.

**Comment by deXxterlab97** [comment]
Weird? All my insight from the past month has always followed the pattern of Monster name (rarely happens, even rarer to even show full health/talk) ->Sword resistance (usually happens) -> Magic resistance (happens frequent enough)-> Talk resistance (rare)

**Comment by aikaterna** [comment]
I will look at this closer when I have time, which is not right now.
