### ISSUE TITLE
Set Bonus are stacked causing 0 xp on some, and -3000 on full sets

### ISSUE THREAD

**Issue by mattpilf** [aikaterna/gobcog#368]
When sets are equipped it adds the previous bonuses of partial sets, which often have negatives. This leads to to say Ainz Ooal set having 0 xp for 8 items, or all the King of Mages, King Titan, and Emporer set having -3000 on stats from bonuses when full. This is why I assume this wasn't the intent.

To fix: take final set bonus *for that set*, but allow multiple different sets with different set bonuses.

**Comment by aikaterna** [comment]
It's like that on purpose. People can strategize different actions based on what they would like to mix and match and boost. There is also a comment on the output of the setinfo command, when you use it with a set, that informs people that multiple additive set bonuses stack.

**Comment by mattpilf** [comment]
> It's like that on purpose. People can strategize different actions based on what they would like to mix and match and boost. There is also a comment on the output of the setinfo command, when you use it with a set, that informs people that multiple additive set bonuses stack.

Why would you have something like the King of Mages go that has charisma go from -3000, to -6000, to 3000? 

Was extra -3000 only justified from items 6, 7, and 8 equipped? Surely a -3000 would've been a full nerf on diplomacy.

Or Ainz Ooal where xp goes from .5, to 0, to .5 again.

Was it your intention to *only* have 0 xp at at items 8 and 9.

**Comment by Drapersniper** [comment]
The intention was for set part bonuses to stack so the full bonus / nerf is given when all pieces are equipped.

nothing that you described is unintentional and will not change.
