### ISSUE TITLE
[Question] Cart rolling items correctly?

### ISSUE THREAD

**Issue by Prequarantine** [aikaterna/gobcog#373]
## Complete these first
- [Y] I confirm that I am the owner of the bot running Adventure.
- [Y] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [Y] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
The cart should maybe have rare items or better on it occasionally?  It seems like it _should_ be rolling these items based on the code, but it simply does not on our server.

## Current Behavior
Summoning the cart by chatting normally results in 0 rare or better items being present on the cart.  All items are normal quality.  I am unsure if this is intentional or not.   All players are currently rebirth 1 or rebirth 2 now, having just started playing a bit ago

## Possible Solution
None if intended cart behavior.  Making it so the cart can spawn better items otherwise.  

## Steps to Reproduce
1.  Chat after cart cd is up, causing the cart to spawn.
2.  See that the cart has no rare items at all.

## Context (Environment)
Oddly despite having done plenty of adventures, my group has seen almost no rare items (EDIT:  Upon checking, we have zero logs of any rare chests at all, but this is probably just bad luck?), and with no way of getting rare items aside from pets, we were just curious.

## Detailed Description
None necessary.  We just don't know how it works and wanted to know if it was really working correctly.    I am very, very sorry if this is not a bug and it is working correctly.  I wanted to just join the Discord to ask, but the link is invalid for some reason, and I could not find another server to ask. 

## Possible Implementation
None necessary.  We just don't know how it works and wanted to know if it was really working correctly.

**Comment by Prequarantine** [comment]
Just tested and figured out the fix, although now the carts break in the other direction for us lmfao.  lines need "self," before rarity string. for example, 

item = await self._genitem(self, "rare")

instead of 

item = await self._genitem("rare")

This bricks our carts in a wholly new and exciting way, but is a vast improvement over getting nothing but commons.

**Comment by aikaterna** [comment]
Fixed in https://github.com/aikaterna/gobcog/commit/7373b19a5ae756719c2db9efd58c8afc0e64e73b

Close guess, but it needed ctx. Thanks for the report.
