### ISSUE TITLE
[Feature Request] Tinkerer adjustments if needed

### ISSUE THREAD

**Issue by McHenche** [aikaterna/gobcog#384]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [ ] Command
- [x] Functionality

## Describe your requested feature
At this moment the tinkerer class is very weak because the int stat only affects it at 2000 and luck at 1000 which you are only able to get at about rebirth 35. Which makes it very useless at lower rebirth levels. 

If the minimum amount of int and luck can be decreased it would be very helpful at the early stages of the game and would make tinkerer a viable class.

And if possible also add a way to manually buff/nerf classes with a command.

**Comment by aikaterna** [comment]
What is your evidence for "At this moment the tinkerer class is very weak because the int stat only affects it at 2000 and luck at 1000 which you are only able to get at about rebirth 35. Which makes it very useless at lower rebirth levels." ? 

"if possible also add a way to manually buff/nerf classes with a command" will not be happening.

**Comment by McHenche** [comment]
I am currently on a server with many other people and almost all of them only use the beserker/wizard/cleric class, because as a tinkerer nobody is able to forge an item that is more useful then the abilities of other classes. The person with the highest rebirths currectly (34) is not able to reach the 2000 int or the 1000 luck stat. And if you don't have at least 2000 int or 1000 luck the forging roll does not change the final stat which makes forging weaker and removes the *luck* aspect from it as well. Currently I'm at rebirth 20 and am not able to forge an item with over 100 on 1 stat, But if i use the wizard class and use the !focus command i can easily do over 200 damage.

**Comment by aikaterna** [comment]
So where are you getting these number values from?

**Comment by McHenche** [comment]
gobcog/blob/master/adventure/class_abilities.py
line 1179 - 1202

modifier_penalty_str and  modifier_penalty_cha get rounded off to -1 instead of 0 so it acts as if you already have 2000 strenght and 1000 charisma (This might be a bug) which stops the forging roll from affecting the weapon because the modifier is too low in the negative.

and because the modifier is set to 0.01 / 10 for luck it only increases the modifier at 1000, and for strenght it's set to 0.01 / 20 so it increases at 2000
