### ISSUE TITLE
[Feature Request] adding convertibility for ascended and set chests

### ISSUE THREAD

**Issue by Dark-lame** [aikaterna/gobcog#390]
# Feature request

## Complete these first
- [X] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [ ] Command
- [X] Functionality

## Describe your requested feature
Existent feature is chest convertibility form normal -> rare -> epic -> legendary. I propose adding convertibility from legendary -> ascended and ascended -> set.

**Comment by aikaterna** [comment]
That won't happen as those are special treasure types and should be gotten through games and not conversions.
