### ISSUE TITLE
[Command Bug] Insight shows false transcended mob

### ISSUE THREAD

**Issue by Dark-lame** [aikaterna/gobcog#391]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [x] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Command name

insight

## Expected Behavior
When a user runs the insight command, if the mob is Transcended it should look something like this:
![image](https://user-images.githubusercontent.com/64549497/176065094-1f7ea7e3-9c3f-40f9-9ab2-a1cce2525a69.png)
Or with the (Transcended) line near the end of the insight response: 
![image](https://user-images.githubusercontent.com/64549497/176065241-1c6cbcd7-030f-4125-aaa1-9b6796556f77.png)

## Current Behavior
adventure version 3.5.3
A special case has occurred: 
![image](https://user-images.githubusercontent.com/64549497/176065563-3f5bff67-edd7-4d13-a90c-0d7c3378b588.png)
There is no "Transcended" in the mob name, but the later (Transcended) is there. 
The raid result is as follows: 
![image](https://user-images.githubusercontent.com/64549497/176065666-1fe5faf4-03cc-4070-83bd-5b88062599fe.png)
It was not a real transcended mob. 
## Possible Solution
Possible solution would be either remove the (Transcended) near the end of the first string to remove the redundancy, if its a separate function, or if it's the highest/most accurate insight one can get. 

## Steps to Reproduce
1. switch to psychic & hardmode if not already
2. pray to RNJesus that you land a transcended mob
3. Check response if it matches above scenario

## Context (Environment)
Has not resulted in any crashes or bot-error response, so it's a QoL fix. However, it would a significant one in case this happens again.

**Comment by Dark-lame** [comment]
sorry aikia i hit enter before i finished. almost done

**Comment by aikaterna** [comment]
Thanks for chatting about it in the support server, for reference for myself for later: https://discord.com/channels/154659242253484033/403297256104787978/991160453248069742

**Comment by Dark-lame** [comment]
as of update 3.5.4: issue is still prevalent:
![image](https://user-images.githubusercontent.com/64549497/179837443-fac394e5-4af6-4855-8c06-4264ef89f8af.png)

This may be unrelated, but since we updated to 3.5.4, no transcended mobs have spawned.  
![image](https://user-images.githubusercontent.com/64549497/179837965-26b80ba1-655f-4ea3-a8e1-466c1db86d7b.png)

For a server of our size and activity, getting no transcended mob for nearly 2 weeks is very unusual.
