### ISSUE TITLE
[Bug] Multiple mob images not loading

### ISSUE THREAD

**Issue by Dark-lame** [aikaterna/gobcog#396]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [x] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior

On easy mode, every mob should have an image on the initial raid message, as shown:
![image](https://user-images.githubusercontent.com/64549497/183273452-8dbd981b-46f5-4f3e-afb4-ffd63ac658e0.png)
This primal light elemental has a working and showing image. 

## Current Behavior
adventure version 3.5.4
The **Gnoll, Fire Wyvern, and Raven** mobs don't have working image links, as shown:
![image](https://user-images.githubusercontent.com/64549497/183273509-8aa22062-c615-40da-aa92-2329a02dc60a.png)
![image](https://user-images.githubusercontent.com/64549497/183273562-2a9685d9-f040-43a6-91f5-e941c12cfc37.png)
![image](https://user-images.githubusercontent.com/64549497/183273582-9a896043-11d0-4de6-ba8c-eb97f8cf115f.png)
All of these mobs have broken image links. 

## Possible Solution
Fix or replace the respective mob images, or their image links. 

## Steps to Reproduce

1. change to easy mode if on hard mode
2. do command !a Gnoll, !a Raven, and !a Fire Wyvern
3. review initial raid message. Image should either be loading or not present at all. 

## Context (Environment)
Has not resulted in any bot errors, so this is a QoL change. However, not seeing the images can be a bit disorienting and confusing on initial sight.

**Comment by aikaterna** [comment]
https://github.com/aikaterna/gobcog/commit/ace3452a188dffe6abd9a8fdbb9153957b1cf0c3
