### ISSUE TITLE
[Bug] More mob image links broken

### ISSUE THREAD

**Issue by Dark-lame** [aikaterna/gobcog#397]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [x] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
On easy mode, every mob should have an image on the initial raid message, as shown:
![image](https://user-images.githubusercontent.com/64549497/184018243-25719e21-0e46-4c0a-85ca-fabcb48e4343.png)

In this instance, the peakcock spirit has a working image. 
## Current Behavior
adventure version 3.5.5
The **bear, earth elemental, air elemental, flatland cougar, possessed sword, and rabid cave bear** mobs have broken image links, as shown:
![image](https://user-images.githubusercontent.com/64549497/184018526-8864fa67-5875-4f9e-8f9e-740ae6b977e8.png)
![image](https://user-images.githubusercontent.com/64549497/184018570-df7ff78b-a87d-4f36-9349-cc88f56cb6a3.png)
![image](https://user-images.githubusercontent.com/64549497/185473373-f590530d-7b38-452f-b007-34e6a79f8b17.png)
![image](https://user-images.githubusercontent.com/64549497/185473453-cd692a78-0316-4de5-b03f-8a2ba9cdf8bf.png)
![image](https://user-images.githubusercontent.com/64549497/185473555-3f2e0fbc-2016-4af5-aeff-3077ec36bf8b.png)
![image](https://user-images.githubusercontent.com/64549497/185473629-fb28b637-1d1d-4c6b-bf09-8667953cd2be.png)

## Possible Solution
Fix or replace the respective mob images, or their image links.

## Steps to Reproduce

1. enable easy mode if not enabled already
2. spawn either of these mobs
3. observe initial raid message with images absent

## Context (Environment)
Has not resulted in any bot errors, so this is a QoL change. However, not seeing the images can be a bit disorienting and confusing on initial sight.

**Comment by Dark-lame** [comment]
8/18/22 edit: added air elemental, flatland cougar, possessed sword, and rabid cave bear

separate but related issue: ice dragon and ice wyvern use the same image:
![image](https://user-images.githubusercontent.com/64549497/185474002-dc8fd0b1-f5f4-4f24-bc96-0f0275decf51.png)
![image](https://user-images.githubusercontent.com/64549497/185474092-893f7c2a-85c9-4ffd-bf11-071dee843073.png)

similar context and course of action needed for this as stated above.

**Comment by aikaterna** [comment]
Thanks for reporting this and keeping it up to date. Fixed in https://github.com/aikaterna/gobcog/commit/490df404a32f7c72a42fef13298d35b89de8a328
