### ISSUE TITLE
[Command Bug] Manually swapping gear loses pet.

### ISSUE THREAD

**Issue by LokVokun** [aikaterna/gobcog#399]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [X] I'm an Adventure user but not the bot owner.
- [X] I confirm that I have checked the [issue tracker](../) and this bug hasn't been reported already.

## Command name

[p]equip

## Expected Behavior

From equipping one type of gear to another type of gear you would reasonably expect to keep your pet. Seems tangentially related to issue #398

## Current Behavior

Adventure version: 3.5.5
After catching a pet swapping from a CHA set of gear to a ATK set of gear I somehow keep losing my pet. I suspect it's from the "set" item. 

## Possible Solution

Pets should be kept after swapping gear and or changing gear templates. 

## Steps to Reproduce

1. Have no pet
2. Spam [p]pet until you get a pet.
3. Swap from CHA gear to ATK gear
4. [p]equip .firm_bone_chain
5. [p]equip Heavenly Dragonbone Sandals
6. [p]equip mithril defender of suffering
7. [p]equip cursed diamond-studded katana
8. [p]equip .bronze_charm
9. type [p]stats, confirm newly acquired pet is missing. 

## Context (Environment)

How has this issue affected you? 
I have lost my Demon Snake, Rainbow Fox, and most recently a striped viper. Therefor losing out on the ability to proc extra EXP drops or forage for loot.
The !unequip all command has also killed my pets in the past too. 

## Detailed Description

Make it so [p]unequip all, swapping gear templates, and swapping gear manually does not murder pets. 

## Possible Implementation

![unknown](https://user-images.githubusercontent.com/113474819/190003863-f82aa74a-7f86-460c-b795-171b9f12f16d.png)

**Comment by LokVokun** [comment]
I was able to re create this bug my removing my chest / gloves.

It appears that the pet is somehow "attached" to the equipped chest (or gloves) armor possibly? 
![Look_What_They_Did_To_My_Boy](https://user-images.githubusercontent.com/113474819/190345895-0ca72fcd-04d5-4eeb-8110-f6b7b916ad08.PNG)

**Comment by aikaterna** [comment]
https://github.com/aikaterna/gobcog/issues/398#issuecomment-1257064138

I'm closing this in favor of tracking this "issue" there.
