### ISSUE TITLE
[Feature Request] Code Block Language Highlighting Change/Configurability

### ISSUE THREAD

**Issue by ComradeCactus** [aikaterna/gobcog#420]
# Feature request

## Complete these first
- [x] I confirm that I have checked the [issue tracker](../) and a this feature request doesn't already exist.

## Select the type of feature you are requesting:

- [x] Command
- [ ] Functionality

## Describe your requested feature
Create an admin/owner-configurable server setting to change highlighting language for the code blocks the game generates via the stats/backpack command.

Discord's latest update to colors/fonts changed the colors used in the CSS code blocks to a teal/grey that makes it difficult for those with colorblindness to read the text of items and levels/stats.

Allowing bot/server administrators to configure the language used in these blocks will allow them to make the game more accessible to users.

Alternatively, update commands to use ml instead of css to increase readability.

**Comment by TrustyJAID** [comment]
Hey there, thanks for making this issue. You're right Discords change to css codeblocks doesn't really line up with how the game should look to us. I have just finished migrating all the old css to ansi which allows us to define the colours more appropriately without special formatting although I have left the old formatting in anyways. At this time I don't plan to support customizing these colours but I could see it being possible in the future, though I've already extended every text colour available in Discord's ansi setting but not background colours. I have included some example images of what I have added including making the old Alarm red again.
![image](https://user-images.githubusercontent.com/4099256/235280194-5b1a3493-48d0-440c-99e0-6e5fa59cc07c.png)
![image](https://user-images.githubusercontent.com/4099256/235280198-7d1fbd94-05fa-46b3-a06c-4b1d972aeb0f.png)
![image](https://user-images.githubusercontent.com/4099256/235280205-f119f877-d011-417c-b8cc-dae6cbc9b5bf.png)
![image](https://user-images.githubusercontent.com/4099256/235280216-3d7dbfd3-176b-4412-ab6e-adbae6f99f82.png)
![image](https://user-images.githubusercontent.com/4099256/235280225-90b2c69f-8eda-42bb-a877-d67ddea9a5be.png)
![image](https://user-images.githubusercontent.com/4099256/235280255-f3ccb0a0-1c54-4a0c-ab55-759bc9e4fc28.png)
