### ISSUE TITLE
[Bug] Set bonuses from the SAME set stack (King Titan/The King of Mages/High Emperor) even when wearing full 10/10 set

### ISSUE THREAD

**Issue by amerett0** [aikaterna/gobcog#422]
As title says, full set bonuses do not take priority and even when wearing the full set, -3000 stats compound both 3pc and 7pc are added.

## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure. (i know the owner)
- [x] I confirm that I have not modified the source code of Adventure.
- [x] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
Set bonuses of DIFFERENT sets should and can stack but if wearing the full 10/10 only the full set bonus should apply.

{Rebirths: 24, 
 Max Level: 210}

A level 122 Bard

Bards can perform to aid their comrades in diplomacy.
Use the music command when being diplomatic in an adventure. 

- ATTACK: -2,868 [+0] - CHARISMA: 688 [+72] - INTELLIGENCE: 107 [+0]

 - DEXTERITY: 250 - LUCK: 80 

- Backpack: 163/170 
- Currency: 1,071,025 
- Experience: 20,504,119/20,638,013 
- Unspent skillpoints: 0

Active bonus: ( -3000 | 0  | -25 | -50 | -50 ) Stats: 70% | EXP: -25% | Credits: 50%
* Daily bonus active

## Current Behavior
Original version
=================================================== 
 Name                                                Slot     ATT   CHA   INT   DEX   LUC   LVL   QTY   DEG   SET          
===================================================
 {Set:''High Emperors Crest''}                       head     0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''Emperors Tear''}                             neck     0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''High Emperors Regalia''}                     chest    0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''High Emperors Grasp''}                       gloves   0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''Basileus Embrace''}                          belt     0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''High Emperors Sovereign Plates''}            legs     0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''High Emperors Grace''}                       boots    0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''Basileus Guard''}                            left     0     30    0     10    0     49    1     N/A   High Emperor 
 {Set:''Basileus Honor''}                            right    0     30    0     10    0     49    1     N/A   High Emperor 
 {Legendary:'Fancy Draconium Ringlet Of The Mind'}   ring     15    42    15    14    14    119   1     [3]   N/A 
 {Set:''Basileus Love''}   charm   0     30    0     10    0     49    1     N/A   High Emperor          
=================================================== 
Page 1
Copy and pasted stats above

## Possible Solution
Please fix!

## Steps to Reproduce

1.Must have complete set to test.
2.
3.
4.

## Context (Environment)

What's the point of having full sets if you still have -3000 atk/cha/int?

I dont code no idea must be just a prioritization maybe?

3 sets have -3000 stats (High Emperor/King Titan/The King of Mages) if you have the full set it still adds up previous partial set bonuses rather than prioritize just the full set bonus.

## Detailed Description
Fix this.

**Comment by aikaterna** [comment]
> but if wearing the full 10/10 only the full set bonus should apply.

Not intended.

> What's the point of having full sets if you still have -3000 atk/cha/int?

Something for users to puzzle out.

> Fix this.

No. You can provide your own theme for adventure where these sets are more balanced to your tastes, or remove them entirely. This comment is rude and entitled.
