### ISSUE TITLE
Extremely high spawn rate of boss / dragons / monsters

### ISSUE THREAD

**Issue by LokVokun** [aikaterna/gobcog#438]
## Complete these first
- [ ] I confirm that I am the owner of the bot running Adventure.
- [ ] I confirm that I have not modified the source code of Adventure.
- [X] I'm an Adventure user but not the bot owner.
- [X] I confirm that I have checked the [issue tracker](../) and this bug hasn't been reported already.

## Command name

!a / !adventure

## Expected Behavior

Normal spread of boss to general monsters. 

## Current Behavior
Adventure version: 4.0.0

There is about an ~80% chance that anybody who starts an adventure will generate a Dragon / Boss encounter. 

## Steps to Reproduce
1. Start an adventure.
2.
3.
4.

## Context (Environment)
This has caused users to become disinterested in the adventure game because it's extremely difficult to solo Dragon / Boss monsters and needing a raid call about 4+ times _an hour_ to get anywhere is quite extreme.

It's possible this drop rate has increased as one specific user has the ability to use hundreds of million/billion/trillion gold to NV and catapult their level to 800+ (of 1000?) 

Is boss rate tied to user level(s) at all? 

Yes, one user was able to NV multiple _trillions_ of gold -- this might be an area to consider investigating of boss rates are tied to user levels / rank / etc somehow. 

## Possible Implementation
![ascoreboard](https://github.com/aikaterna/gobcog/assets/113474819/cd2bdbf8-9b63-4f91-ace9-6717bd3c4d64)
![NVSB](https://github.com/aikaterna/gobcog/assets/113474819/9e91da4e-6ca3-4625-b1c7-7c9566f3897c)

**Comment by aikaterna** [comment]
Hi, please post this on the pinned issue for Adventure 4.0 issues instead: https://github.com/aikaterna/gobcog/issues/423

I would move it for you but there's no issue migration to a currently open one. Thanks in advance.
