### ISSUE TITLE
2 handed unequip issue

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/gobcog#63]
Unequipping a 2h item makes 2 of the item appear in the backpack.

**Comment by Redisics** [comment]
`else:
                for current_item in c.current_equipment():
                    log.info(current_item)
                    if item.lower() in current_item.name.lower():
                        await c._unequip_item(current_item)
                        log.info("is that a loop")
                        msg += _(
                            "{author} removed the {current_item} and put it into their backpack."
                        ).format(author=self.E(ctx.author.display_name), current_item=current_item)`
into
`else:
                for current_item in c.current_equipment():
                    log.info(current_item)
                    if item.lower() in current_item.name.lower():
                        await c._unequip_item(current_item)
                        log.info("is that a loop")
                        msg += _(
                            "{author} removed the {current_item} and put it into their backpack."
                        ).format(author=self.E(ctx.author.display_name), current_item=current_item)
                        if len(str(current_item.slot)) > 1:
                            log.info("two slot handled")
                            break`
