### ISSUE TITLE
Item Classification / Naming rather pointless

### ISSUE THREAD

**Issue by skylarr1227** [aikaterna/gobcog#90]
From every game I've played within the rpg genre that has items of various quality-the names of the items mean something. While it's possible you meant it to be this way... Currently the names mean nothing.

Legendary: Godly cloth hat (0, 0, 0, 2 , 1) 
Stuff like that. Monsters follow the same pattern as do pets.
The whole feel seems a bit rushed and the names just make it sound odd. I'll post screen shots following this.

**Comment by skylarr1227** [comment]
Also, items like "Dented Cloth Longsword" or "Bent Hide Crossbow" are more examples of things that shouldn't be.

**Comment by skylarr1227** [comment]
![Screenshot_20200201-214733](https://user-images.githubusercontent.com/44381751/73602141-e32db800-453c-11ea-80b4-da985d85f4d6.png)
I guess maybe, an iron rope? maybe.
![Screenshot_20200201-214835](https://user-images.githubusercontent.com/44381751/73602146-f3de2e00-453c-11ea-8ae9-51d9e2984b7a.png)
PERFECT example. Polished hide Longsword 

![Screenshot_20200201-214852](https://user-images.githubusercontent.com/44381751/73602152-03f60d80-453d-11ea-8940-eb76b6e2edb5.png)
Ancient is spelled Ancienty, and copper is Cooper.

![Screenshot_20200201-215021](https://user-images.githubusercontent.com/44381751/73602158-16704700-453d-11ea-856e-e5bf2062c4b0.png)
This sounds like a item better than useless. guess not.

And the biggest point I'd like to to make here... Is that every rarity of item, has the same materials, and the same adjectives describing. 
There should be something like:

 Copper, Tin, Iron, Steel
for common metal class items.  
 Cloth, Hide, Leather, Fur, Silk
for common non-metal items. (Yes there is more in each of these just gave examples)

 Gold, Various gemstone, Dragonbone etc
For RARE weapons and such

Dragonscale, Spider-Silk, Elven, Etc
for RARE cloth/armor etc.

however currently..... there is the same Ancienty Cooper items, in every rarity, the only difference is the random generated stats. 

Amount of items doesn't matter to me, when there is only really a couple hundred unique choices at best.... The rest are just repeats with rnd stats.

Maybe this was intentional, if so, then so be it.... I guess

**Comment by aikaterna** [comment]
You can make your own items if you want and you don't have to use the default ones.

**Comment by skylarr1227** [comment]
The issue here isn't resolved. Your cog has gone from good, to lazy, to bad. It's unfortunate.
