### ISSUE TITLE
[Change Log] Some spelling errors

### ISSUE THREAD

**Issue by Menteroth** [aikaterna/gobcog#97]
Some have been changed already. Just adding this to be seen.

https://ptb.discordapp.com/channels/240154543684321280/240212783503900673/674739667567902741

**Comment by Drapersniper** [comment]
Not to nitpick, but would be nice to have the actual suggestion here, rather than having an url that directs you to the message (For example that forces me to login with my 2FA)

**Comment by Menteroth** [comment]
That's fine. You weren't there when the discussion occured and I did ask before I made the issue if I should copy and paste or post the URL. Aika said it was fine with the URL so I went with it. But I will think about that in the future.

Here is the post as well.
"You will get `a better items` from loot chests" `>>`better items

"Character `will` more rebirths will be able to convert lesser loot chest into higher quality loot chests" `>>`with

"Characters `will` more rebirths will have their skill cooldowns significantly reduced" `>>`with

"Immortal monsters have been living since the `begging` of time itself, many adventurers have tried to kill them but only to fails." `>>`beginning

"Due to the increased number of items, the Basilisk now be stopped with any `Shinny` items." `>>`shiny

"Ascended monsters `are monster` who have obtained the power to level up" `>>`are monsters

"`These monster` may also have very different weaknesses or strengths when compared to their non ascended counter parts" `>>`These monsters

"Killing these `beats` will award `your` with significantly more experience and currency, but are you worthy of their rewards?" `>>`beasts | you

"A character `wit ha` higher number of rebirths has a chance of spawning stronger monster" `>>`with a

"You are now no longer able to join an adventure without any currency and will require at least `250` of your local currency." `>>`When I tried first time after update it said 500.

**Comment by Drapersniper** [comment]
Awesome, thanks I'll take a loot at these eventually if aika doesn't do it first.

The text you are refering to is something i put together to aika last minute so it could be used as a reference for the changes that went in at that point, since there was so many and it was a fundamental mechanics change.

Was never intended to be an official doc so spelling/grammer wasn't checked.
